### ISSUE TITLE
http_client Telemetry broken?

### ISSUE THREAD

**Issue by stakach** [wyhaines/opentelemetry-instrumentation.cr#22]
There seems to be a breaking change between these two commits:

```
  opentelemetry-instrumentation:
    git: https://github.com/wyhaines/opentelemetry-instrumentation.cr.git
    version: 0.3.3+git.commit.551543ad0f4e5d7eefdb5277809493e154e4f5c2
    version: 0.3.3+git.commit.8fae1e32b960c77abeae7b7da0d03f7994acd0ea
```

building projects now errors with

```
Error: instantiating 'previous_def(HTTP::Request)'


In lib/opentelemetry-instrumentation/src/opentelemetry/instrumentation/crystal/http_client.cr:6:23

 6 | #
                           ^------
Error: undefined method 'in_span' for OpenTelemetry:Module

OpenTelemetry:Module trace:

  lib/opentelemetry-instrumentation/src/opentelemetry/instrumentation/crystal/http_client.cr:6
```

**Comment by wyhaines** [comment]
It probably is in main, because the current commits depends on an addition to the API/SDK side of things that has not been released yet. The new release is happening today, for both the API/SDK and the instrumentation.

**Comment by wyhaines** [comment]
With the release that I just did, it should be fixed.  *knock on wood*

Tomorrow I am working on bringing up an instrumented copy of PlaceOS locally, so hopefully all of the bad bugs are dealt with. Thanks @stakach !
